# Generated by Django 2.2.4 on 2019-08-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfosConfig',
            fields=[
                ('pk_id', models.AutoField(max_length=32, primary_key=True, serialize=False, verbose_name='配置文件主键')),
                ('key', models.CharField(max_length=128, verbose_name='属性')),
                ('value', models.CharField(max_length=128, verbose_name='属性值')),
                ('comments', models.CharField(max_length=256, null=True, verbose_name='备注')),
                ('version', models.CharField(max_length=8, verbose_name='版本号')),
                ('source', models.CharField(max_length=128, verbose_name='来源')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='删除标识')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pk_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=128, verbose_name='患者姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('ID', models.CharField(max_length=32, verbose_name='身份证号码')),
                ('addr', models.CharField(max_length=256, verbose_name='地址')),
                ('sex',
                 models.CharField(choices=[('1', '男'), ('4', '女'), ('9', '未知')], max_length=2, verbose_name='性别')),
                ('out_flag', models.BooleanField(default=False, verbose_name='门诊标识')),
                ('out_time', models.DateTimeField(blank=True, verbose_name='看诊登记时间')),
                ('in_flag', models.BooleanField(default=False, verbose_name='住院标识')),
                ('in_time', models.DateTimeField(blank=True, verbose_name='住院时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='出院时间')),
                ('book_flag', models.BooleanField(default=False, verbose_name='预约标识')),
                ('book_time', models.DateTimeField(blank=True, verbose_name='预约看诊时间')),
                ('pre_time', models.DateTimeField(blank=True, verbose_name='预约登进士时间')),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='记录删除标识')),
                ('deleted_time', models.DateTimeField(blank=True, verbose_name='删除时间')),
                ('dept_code', models.CharField(max_length=10, verbose_name='科室编码')),
                ('dept_name', models.CharField(max_length=32, verbose_name='科室名称')),
                ('doc_code', models.CharField(max_length=10, verbose_name='医生编码')),
                ('doc_name', models.CharField(max_length=32, verbose_name='医生姓名')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
        ),
    ]
