# Generated by Django 2.2.4 on 2019-08-17 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infosconfig',
            old_name='pk_id',
            new_name='pki_id',
        ),
    ]
