# Generated by Django 2.2.4 on 2019-09-05 00:39

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('infos', '0003_auto_20190817_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 文章标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
