# Generated by Django 2.2.4 on 2019-09-12 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('infos', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosconfig',
            options={'verbose_name': '配置信息', 'verbose_name_plural': '配置信息'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者信息表', 'verbose_name_plural': '患者信息表'},
        ),
    ]
